---
title: Time-lapse animations with a Raspberry Pi
hero_image: images/banner.png
description: Learn how to setup a Pi Camera to take time-lapse pictures
original_url: https://raspberrypi.org/learning/timelapse-setup
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: photography
technologies: raspberry-pi, electronic-components, python, pi-camera
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Time-lapse animations with a Raspberry Pi
- title: Taking a picture
- title: Taking multiple images
- title: Making a GIF
- title: Reducing the file size
- title: Adding a delay
- title: What next?